---
image: node:12
definitions:
  caches:
    jest: .jest
    npm: ~/.npm
    sonar: ~/.sonar/cache
pipelines:
  pull-requests:
    '**':
      - parallel:
          - step:
              name: Validate commits
              image: peakfijn/commitlint
              script:
                - commitlint --to HEAD
          - step:
              name: Validate code
              caches:
                - jest
                - npm
              script:
                - cp .env.example .env
                - npm ci
                - npm run lint
                - npm run test
                - npm run build
          - step:
              name: Analyse code
              image: bycedric/ci-sonarcloud
              caches:
                - sonar
              script:
                - git fetch --unshallow || git fetch
                - sonar-bitbucket
  branches:
    develop:
      - parallel:
          - step:
              name: Validate code
              caches:
                - jest
                - npm
              script:
                - cp .env.example .env
                - npm ci
                - npm run lint
                - npm run test
                - npm run build
          - step:
              name: Analyse code
              image: bycedric/ci-sonarcloud
              caches:
                - sonar
              script:
                - git fetch --unshallow || git fetch
                - sonar-bitbucket
      - step:
          name: Create new release
          image: peakfijn/release-react
          trigger: manual
          script:
            - semantic-release
    master:
      - step:
          name: Deploy to staging
          image: bycedric/ci-heroku
          deployment: staging
          script:
            - heroku whoami
            - git status
            - git fetch --unshallow || git fetch
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_STAGING.git HEAD:master --force
      - step:
          name: Deploy to production
          image: bycedric/ci-heroku
          deployment: production
          trigger: manual
          script:
            - heroku whoami
            - git status
            - git fetch --unshallow || git fetch
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_PRODUCTION.git HEAD:master --force
