---
name: Templates CI
on:
  pull_request:
    paths:
      - 'templates/**'
    paths-ignore:
      - 'templates/package/**'
jobs:
  ci:
    name: Install, validate and build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [10, 12]
        template: [project]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm ci
        working-directory: templates/${{ matrix.template }}
      - run: npm run lint
        working-directory: templates/${{ matrix.template }}
      - run: npm run test
        working-directory: templates/${{ matrix.template }}
      - run: npm run build
        working-directory: templates/${{ matrix.template }}
